package com.hazrat.allahNames.ui.namesofallah

import androidx.annotation.DrawableRes
import com.hazrat.ui.R

@DrawableRes
fun getNameOfAllahIcon(number: Int): Int {
    return when (number) {
        1 -> R.drawable._01_ar_rahmaan
        2 -> R.drawable._02_ar_raheem
        3 -> R.drawable._03_al_malik
        4 -> R.drawable._04_al_quddus
        5 -> R.drawable._05_as_salam
        6 -> R.drawable._06_al_mumin
        7 -> R.drawable._07_al_muhaymin
        8 -> R.drawable._08_al_aziz
        9 -> R.drawable._09_al_jabbar
        10 -> R.drawable._10_al_mutakabbir
        11 -> R.drawable._11_al_khaaliq
        12 -> R.drawable._12_al_baari
        13 -> R.drawable._13_al_musawwir
        14 -> R.drawable._14_al_ghaffar
        15 -> R.drawable._15_al_qahhar
        16 -> R.drawable._16_al_wahhaab
        17 -> R.drawable._17_al_razzaaq
        18 -> R.drawable._18_al_fattaah
        19 -> R.drawable._19_al_aleem
        20 -> R.drawable._20_al_qaabid
        21 -> R.drawable._21_al_baasit
        22 -> R.drawable._22_al_khaafidh
        23 -> R.drawable._23_ar_raafi
        24 -> R.drawable._24_al_muizz
        25 -> R.drawable._25_al_muzil
        26 -> R.drawable._26_as_samee
        27 -> R.drawable._27_al_baseer
        28 -> R.drawable._28_al_hakam
        29 -> R.drawable._29_al
        30 -> R.drawable._30_al_lateef
        31 -> R.drawable._31_al_khabeer
        32 -> R.drawable._32_al_haleem
        33 -> R.drawable._33_al_atheem
        34 -> R.drawable._34_al_ghafoor
        35 -> R.drawable._35_ash_shakoor
        36 -> R.drawable._36_al_alee
        37 -> R.drawable._37_al_kabeer_1
        38 -> R.drawable._38_al_hafeedh
        39 -> R.drawable._39_al_muqeet
        40 -> R.drawable._40_al_haseeb
        41 -> R.drawable._41_al_jaleel
        42 -> R.drawable._42_al_kareem
        43 -> R.drawable._43_ar_raqeeb
        44 -> R.drawable._44_al_mujeeb
        45 -> R.drawable._45_al_waasi
        46 -> R.drawable._46_al_hakeem
        47 -> R.drawable._47_al_wadood
        48 -> R.drawable._48_al_majeed
        49 -> R.drawable._49_al_baith
        50 -> R.drawable._50_ash_shaheed
        51 -> R.drawable._51_al_haqq
        52 -> R.drawable._52_al_wakeel
        53 -> R.drawable._53_al_qawiyy
        54 -> R.drawable._54_al_mateen
        55 -> R.drawable._55_al_waliyy
        56 -> R.drawable._56_al_hameed
        57 -> R.drawable._57_al_muhsee
        58 -> R.drawable._58_al_mubdi
        59 -> R.drawable._59_al_muid
        60 -> R.drawable._60_al_muhyee
        61 -> R.drawable._61_al_mumeet
        62 -> R.drawable._62_al_hayy
        63 -> R.drawable._63_al_qayyoom
        64 -> R.drawable._64_al_waajid
        65 -> R.drawable._65_al_maajid
        66 -> R.drawable._66_al_waahid
        67 -> R.drawable._67_al_ahad
        68 -> R.drawable._68_as_samad
        69 -> R.drawable._69_al_qadir
        70 -> R.drawable._70_al_muqtadir
        71 -> R.drawable._71_al_muqaddim
        72 -> R.drawable._72_al_muakhkhir
        73 -> R.drawable._73_al_awwal_1
        74 -> R.drawable._74_al_aakhir
        75 -> R.drawable._75_az_dhaahir
        76 -> R.drawable._76_al_baatin
        77 -> R.drawable._77_al_waali
        78 -> R.drawable._78_al_mutaali_1
        79 -> R.drawable._79_al_barr
        80 -> R.drawable._80_at_tawwab
        81 -> R.drawable._81_al_muntaqim
        82 -> R.drawable._82_al_afuww
        83 -> R.drawable._83_ar_raoof
        84 -> R.drawable._84_maalik_ul_mulk
        85 -> R.drawable._85_dhul_jalaali_wal_ikraam
        86 -> R.drawable._86_al_muqsit
        87 -> R.drawable._87_al_jaami
        88 -> R.drawable._88_al_ghaniyy
        89 -> R.drawable._89_al_mughni
        90 -> R.drawable._90_al_mani
        91 -> R.drawable._91_ad_dharr
        92 -> R.drawable._92_an_nafi
        93 -> R.drawable._93_an
        94 -> R.drawable._94_al_haadi
        95 -> R.drawable._95_al_badee
        96 -> R.drawable._96_al_baaqi
        97 -> R.drawable._97_al_waarith
        98 -> R.drawable._98_ar_rasheed
        99 -> R.drawable._99_as_saboor
        else -> R.drawable.premium_circle
    }
}
