PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `allah_names` (`number` INTEGER NOT NULL, `enDesc` TEXT NOT NULL, `enMeaning` TEXT NOT NULL, `found` TEXT NOT NULL, `name` TEXT NOT NULL, `transliteration` TEXT NOT NULL, `bnTransliteration` TEXT NOT NULL, `bnMeaning` TEXT NOT NULL, `bnDec` TEXT, PRIMARY KEY(`number`));
INSERT INTO allah_names VALUES(1,'He who wills goodness and mercy for all His creatures','The Beneficent','(1:3)(17:110)','الرَّحْمَنُ','Ar-Rahman','আর-রাহমান','পরম করুণাময়',NULL);
INSERT INTO allah_names VALUES(2,'He who acts with extreme kindness','The Merciful','(2:163)(3:31)(4:100)(5:3)','الرَّحِيمُ','Ar-Raheem','আর-রাহীম','পরম দয়ালু',NULL);
INSERT INTO allah_names VALUES(3,'The Sovereign Lord, The One with the complete Dominion','The King / Eternal Lord','(20:114)(23:116)(59:23)(62:1)','الْمَلِكُ','Al-Malik','আল-মালিক','সার্বভৌম ক্ষমতার অধিকারী',NULL);
INSERT INTO allah_names VALUES(4,'The One who is pure from any imperfection','The Purest','(59:23)(62:1)','الْقُدُّوسُ','Al-Quddus','আল-কুদ্দুস','মহাপবিত্র ও নিষ্কলুষ',NULL);
INSERT INTO allah_names VALUES(5,'The source of peace and security','The Source of Peace','(59:23)','السَّلاَمُ','As-Salam','আস-সালাম','শান্তিদাতা ও ত্রুটিমুক্ত',NULL);
INSERT INTO allah_names VALUES(6,'The inspirer of faith and security','The Inspirer of Faith','(59:23)','الْمُؤْمِنُ','Al-Mu''min','আল-মুমিন','নিরাপত্তা ও ঈমান দানকারী',NULL);
INSERT INTO allah_names VALUES(7,'The guardian and protector of all','The Guardian','(59:23)','الْمُهَيْمِنُ','Al-Muhaymin','আল-মুহাইমিন','অভিভাবক ও সংরক্ষক',NULL);
INSERT INTO allah_names VALUES(8,'The All-Mighty, The Honorable','The All-Mighty','(3:6)(4:158)(9:40)(48:7)','الْعَزِيزُ','Al-Azeez','আল-আযীয','মহাপরাক্রমশালী',NULL);
INSERT INTO allah_names VALUES(9,'The Irresistible, The Compeller','The Compeller','(59:23)','الْجَبَّارُ','Al-Jabbar','আল-জাব্বার','সর্বশক্তিমান ও দুর্বার',NULL);
INSERT INTO allah_names VALUES(10,'The Supreme, The Majestic','The Greatest','(59:23)','الْمُتَكَبِّرُ','Al-Mutakabbir','আল-মুতাকাব্বির','মহিমান্বিত ও শ্রেষ্ঠত্বের অধিকারী',NULL);
INSERT INTO allah_names VALUES(11,'The Creator of everything','The Creator','(6:102)(13:16)(39:62)(40:62)(59:24)','الْخَالِقُ','Al-Khaliq','আল-খালিক','সৃষ্টিকর্তা',NULL);
INSERT INTO allah_names VALUES(12,'The Originator, The Maker','The Maker of Order','(59:24)','الْبَارِئُ','Al-Bari''','আল-বারী','উদ্ভাবক ও রূপদানকারী',NULL);
INSERT INTO allah_names VALUES(13,'The Fashioner of forms','The Shaper of Beauty','(59:24)','الْمُصَوِّرُ','Al-Musawwir','আল-মুসাউয়ির','আকৃতি দানকারী',NULL);
INSERT INTO allah_names VALUES(14,'The Perpetual Forgiver','The Forgiving','(20:82)(38:66)(39:5)(40:42)(71:10)','الْغَفَّارُ','Al-Ghaffar','আল-গাফফার','পরম ক্ষমাশীল',NULL);
INSERT INTO allah_names VALUES(15,'The Subduer, The All-Dominant','The Subduer','(13:16)(14:48)(38:65)(39:4)(40:16)','الْقَهَّارُ','Al-Qahhar','আল-কাহ্‌হার','মহাপরাক্রান্ত ও কঠোর',NULL);
INSERT INTO allah_names VALUES(16,'The Bestower of all gifts','The Giver of All','(3:8)(38:9)(38:35)','الْوَهَّابُ','Al-Wahhab','আল-ওয়াহহাব','মহান দাতা',NULL);
INSERT INTO allah_names VALUES(17,'The Provider, The Sustainer','The Sustainer','(51:58)','الرَّزَّاقُ','Ar-Razzaq','আর-রায্‌যাক','রিযিকদাতা',NULL);
INSERT INTO allah_names VALUES(18,'The Opener, The Victory Giver','The Opener','(34:26)','الْفَتَّاحُ','Al-Fattah','আল-ফাত্তাহ','উন্মোচনকারী ও বিজয়দানকারী',NULL);
INSERT INTO allah_names VALUES(19,'The All-Knowing, The Omniscient','The Knower of All','(2:158)(3:92)(4:35)(24:41)(33:40)','اَلْعَلِيْمُ','Al-''Aleem','আল-আলীম','সর্বজ্ঞাত',NULL);
INSERT INTO allah_names VALUES(20,'The Withholder, The Constrictor','The Constrictor','(2:245)','الْقَابِضُ','Al-Qabid','আল-কাবিদ','সংকীর্ণকারী ও নিয়ন্ত্রণকারী',NULL);
INSERT INTO allah_names VALUES(21,'The Expander, The Reliever','The Reliever','(2:245)','الْبَاسِطُ','Al-Basit','আল-বাসিত','প্রশস্তকারী',NULL);
INSERT INTO allah_names VALUES(22,'The Abaser, The Humbler','The Abaser','(95:5)','الْخَافِضُ','Al-Khafid','আল-খাফিদ','অবনতকারী',NULL);
INSERT INTO allah_names VALUES(23,'The Exalter, The Elevator','The Exalter','(58:11)(6:83)','الرَّافِعُ','Ar-Rafi''','আর-রাফি','উন্নীতকারী ও মর্যাদা দানকারী',NULL);
INSERT INTO allah_names VALUES(24,'The Bestower of Honor','The Bestower of Honour','(3:26)','الْمُعِزُّ','Al-Mu''izz','আল-মুইয্য','সম্মানদানকারী',NULL);
INSERT INTO allah_names VALUES(25,'The Dishonorer, The Humiliator','The Humiliator','(3:26)','المُذِلُّ','Al-Mudhill','আল-মুযিল্ল','অপমানকারী',NULL);
INSERT INTO allah_names VALUES(26,'The All-Hearing','The Hearer of All','(2:127)(2:256)(8:17)(49:1)','السَّمِيعُ','As-Sami''','আস-সামী','সর্বশ্রোতা',NULL);
INSERT INTO allah_names VALUES(27,'The All-Seeing','The Seer of All','(4:58)(17:1)(42:11)(42:27)','الْبَصِيرُ','Al-Baseer','আল-বাসীর','সর্বদ্রষ্টা',NULL);
INSERT INTO allah_names VALUES(28,'The Judge, The Impartial Arbiter','The Judge','(22:69)','الْحَكَمُ','Al-Hakam','আল-হাকাম','পরম বিচারক',NULL);
INSERT INTO allah_names VALUES(29,'The Just, The Equitable','The Just','(6:115)','الْعَدْلُ','Al-''Adl','আল-আদল','পরম ন্যায়বান',NULL);
INSERT INTO allah_names VALUES(30,'The Subtle One, The Kind','The Subtle One','(6:103)(22:63)(31:16)(33:34)','اللَّطِيفُ','Al-Lateef','আল-লাতীফ','অতি সূক্ষ্মদর্শী ও স্নেহশীল',NULL);
INSERT INTO allah_names VALUES(31,'The All-Aware','The All Aware','(6:18)(17:30)(49:13)(59:18)','الْخَبِيرُ','Al-Khabeer','আল-খাবীর','সর্ববিষয়ে সম্যক অবগত',NULL);
INSERT INTO allah_names VALUES(32,'The Forbearing, The Clement','The Forbearing','(2:235)(17:44)(22:59)(35:41)','الْحَلِيمُ','Al-Haleem','আল-হালীম','পরম ধৈর্যশীল',NULL);
INSERT INTO allah_names VALUES(33,'The Magnificent, The Supreme','The Magnificent','(2:255)(42:4)(56:96)','الْعَظِيمُ','Al-''Azeem','আল-আযীম','মহামহিমান্বিত',NULL);
INSERT INTO allah_names VALUES(34,'The All-Forgiving','The Great Forgiver','(2:173)(8:69)(16:110)(41:32)','الْغَفُورُ','Al-Ghafoor','আল-গাফূর','মহাক্ষমাশীল',NULL);
INSERT INTO allah_names VALUES(35,'The Appreciative, The Rewarder','The Rewarder of Thankfulness','(35:30)(35:34)(42:23)(64:17)','الشَّكُورُ','Ash-Shakoor','আশ-শাকূর','গুণগ্রাহী ও পুরষ্কারদাতা',NULL);
INSERT INTO allah_names VALUES(36,'The Most High, The Exalted','The Highest','(4:34)(31:30)(42:4)(42:51)','الْعَلِيُّ','Al-''Aliyy','আল-আলী','সুউচ্চ ও মহীয়ান',NULL);
INSERT INTO allah_names VALUES(37,'The Most Great','The Greatest','(13:9)(22:62)(31:30)','الْكَبِيرُ','Al-Kabeer','আল-কাবীর','সর্বশ্রেষ্ঠ ও সর্বাপেক্ষা মহান',NULL);
INSERT INTO allah_names VALUES(38,'The Preserver, The Protector','The Preserver','(11:57)(34:21)(42:6)','الْحَفِيظُ','Al-Hafeez','আল-হাফীয','মহা সংরক্ষক',NULL);
INSERT INTO allah_names VALUES(39,'The Sustainer, The Nourisher','The Sustainer','(4:85)','المُقيِت','Al-Muqeet','আল-মুকীত','জীবনোপকরণ ও খাদ্যদাতা',NULL);
INSERT INTO allah_names VALUES(40,'The Reckoner, The Sufficient','The Reckoner','(4:6)(4:86)(33:39)','الْحسِيبُ','Al-Haseeb','আল-হাসীব','পুঙ্খানুপুঙ্খ হিসাব গ্রহণকারী',NULL);
INSERT INTO allah_names VALUES(41,'The Majestic, The Sublime','The Majestic','(55:27)(39:14)(7:143)','الْجَلِيلُ','Al-Jaleel','আল-জালীল','পরম মর্যাদাবান ও প্রতাপশালী',NULL);
INSERT INTO allah_names VALUES(42,'The Generous, The Bountiful','The Most Generous','(27:40)(82:6)','الْكَرِيمُ','Al-Kareem','আল-কারীম','পরম উদার ও অনুগ্রহকারী',NULL);
INSERT INTO allah_names VALUES(43,'The Watchful, The Observer','The Watchful One','(4:1)(5:117)','الرَّقِيبُ','Ar-Raqeeb','আর-রাক্বীব','সদাসতর্ক ও পর্যবেক্ষক',NULL);
INSERT INTO allah_names VALUES(44,'The Responsive, The Answerer','The Responder to Prayer','(11:61)','الْمُجِيبُ','Al-Mujeeb','আল-মুক্বীব','দোয়া কবুলকারী',NULL);
INSERT INTO allah_names VALUES(45,'The All-Encompassing, The Boundless','The All-Encompassing','(2:268)(3:73)(5:54)','الْوَاسِعُ','Al-Wasi''','আল-ওয়াসি','সর্বত্র বিরাজমান ও অসীম',NULL);
INSERT INTO allah_names VALUES(46,'The Wise, The Possessor of Wisdom','The Perfectly Wise','(31:27)(46:2)(57:1)(66:2)','الْحَكِيمُ','Al-Hakeem','আল-হাকীম','পরম প্রজ্ঞাবান',NULL);
INSERT INTO allah_names VALUES(47,'The Most Loving, The Affectionate','The Most Loving','(11:90)(85:14)','الْوَدُودُ','Al-Wadood','আল-ওয়াদূদ','পরম স্নেহশীল ও প্রেমময়',NULL);
INSERT INTO allah_names VALUES(48,'The Most Glorious, The Honorable','The Glorious One','(11:73)','الْمَجِيدُ','Al-Majeed','আল-মাজীদ','অতি মর্যাদাপূর্ণ ও সম্মানিত',NULL);
INSERT INTO allah_names VALUES(49,'The Resurrector, The Raiser of the Dead','The Resurrector','(22:7)','الْبَاعِثُ','Al-Ba''ith','আল-বাইস','পুনরুত্থানকারী',NULL);
INSERT INTO allah_names VALUES(50,'The Witness, The All-Observing','The Witness','(4:166)(22:17)(41:53)(48:28)','الشَّهِيدُ','Ash-Shaheed','আশ-শাহীদ','প্রত্যক্ষদর্শী ও সর্বসাক্ষী',NULL);
INSERT INTO allah_names VALUES(51,'The Absolute Truth','The Truth','(6:62)(22:6)(23:116)(24:25)','الْحَقُّ','Al-Haqq','আল-হাক্ব','পরম সত্য',NULL);
INSERT INTO allah_names VALUES(52,'The Trustee, The Dependable','The Trustee','(3:173)(4:171)(28:28)(73:9)','الْوَكِيلُ','Al-Wakeel','আল-ওয়াকীল','পরম নির্ভরযোগ্য অভিভাবক',NULL);
INSERT INTO allah_names VALUES(53,'The Most Strong, The All-Powerful','The Possessor of Strength','(22:40)(22:74)(42:19)(57:25)','الْقَوِيُّ','Al-Qawiyy','আল-ক্বাবিয়্যু','মহাশক্তিধর',NULL);
INSERT INTO allah_names VALUES(54,'The Firm, The Steadfast','The Forceful','(51:58)','الْمَتِينُ','Al-Mateen','আল-মাতীন','সুদৃঢ় ও অটল',NULL);
INSERT INTO allah_names VALUES(55,'The Protecting Friend, The Supporter','The Protector','(4:45)(7:196)(42:28)(45:19)','الْوَلِيُّ','Al-Waliyy','আল-ওয়ালিয়্যু','পরম বন্ধু ও অভিভাবক',NULL);
INSERT INTO allah_names VALUES(56,'The Praiseworthy, The All-Lauded','The Praised','(14:8)(31:12)(31:26)(41:42)','الْحَمِيدُ','Al-Hameed','আল-হামীদ','সকল প্রশংসার অধিকারী',NULL);
INSERT INTO allah_names VALUES(57,'The Accounter, The Numberer of All','The Counter','(72:28)(78:29)(82:10-12)','الْمُحْصِي','Al-Muhsi','আল-মুহসী','সর্বগণনাকারী ও সর্বদ্রষ্টা',NULL);
INSERT INTO allah_names VALUES(58,'The Originator, The Producer','The Originator','(10:34)(27:64)(29:19)(85:13)','الْمُبْدِئُ','Al-Mubdi''','আল-মুবদী','সৃষ্টির সূচনাকারী',NULL);
INSERT INTO allah_names VALUES(59,'The Restorer, The Recreator','The Restorer','(10:34)(27:64)(29:19)(85:13)','الْمُعِيدُ','Al-Mu''eed','আল-মুঈদ','পুনঃসৃষ্টিকারী',NULL);
INSERT INTO allah_names VALUES(60,'The Giver of Life','The Giver of Life','(7:158)(15:23)(30:50)(57:2)','الْمُحْيِي','Al-Muhyee','আল-মুহয়ী','জীবনদানকারী',NULL);
INSERT INTO allah_names VALUES(61,'The Creator of Death, The Destroyer','The Taker of Life','(3:156)(7:158)(15:23)(57:2)','اَلْمُمِيتُ','Al-Mumeet','আল-মুমীত','মৃত্যুদানকারী',NULL);
INSERT INTO allah_names VALUES(62,'The Ever-Living','The Ever Living','(2:255)(3:2)(25:58)(40:65)','الْحَيُّ','Al-Hayy','আল-হায়্য','চিরঞ্জীব',NULL);
INSERT INTO allah_names VALUES(63,'The Self-Existing, The Sustainer','The Self Existing','(2:255)(3:2)(20:111)','الْقَيُّومُ','Al-Qayyoom','আল-ক্বাইয়্যূম','সবকিছুর ধারক ও স্বয়ম্ভূ',NULL);
INSERT INTO allah_names VALUES(64,'The Perceiver, The Finder','The Perceiver','(38:44)','الْوَاجِدُ','Al-Wajid','আল-ওয়াজিদ','যা ইচ্ছা তাই পান এমন',NULL);
INSERT INTO allah_names VALUES(65,'The Glorious, The Illustrious','The Glorious','(11:73)','الْمَاجِدُ','Al-Majid','আল-মাজিদ','মহান ও সম্মানিত',NULL);
INSERT INTO allah_names VALUES(66,'The Unique, The Single','The Only One','(2:163)(5:73)(9:31)(18:110)','الْواحِدُ','Al-Wahid','আল-ওয়াহিদ','এক ও অদ্বিতীয়',NULL);
INSERT INTO allah_names VALUES(67,'The One, The Indivisible','The One','(112:1)','اَلاَحَدُ','Al-Ahad','আল-আহাদ','একক সত্তা',NULL);
INSERT INTO allah_names VALUES(68,'The Eternal Refuge, The Self-Sufficient','The Supreme Provider','(112:2)','الصَّمَدُ','As-Samad','আস-সামাদ','অমুখাপেক্ষী ও পরম আশ্রয়',NULL);
INSERT INTO allah_names VALUES(69,'The Capable, The Powerful','The Powerful','(6:65)(36:81)(46:33)(75:40)','الْقَادِرُ','Al-Qadir','আল-ক্বাদির','সর্বশক্তিমান',NULL);
INSERT INTO allah_names VALUES(70,'The Omnipotent, The Determiner','The Creator of All Power','(18:45)(54:42)(54:55)','الْمُقْتَدِرُ','Al-Muqtadir','আল-মুক্বতাদির','পরম প্রভাব ও ক্ষমতার অধিকারী',NULL);
INSERT INTO allah_names VALUES(71,'The Expediter, The Promoter','The Expediter','(16:61)(17:34)','الْمُقَدِّمُ','Al-Muqaddim','আল-মুকাদ্দিম','অগ্রবর্তীকারী',NULL);
INSERT INTO allah_names VALUES(72,'The Delayer, The Postponer','The Delayer','(71:4)','الْمُؤَخِّرُ','Al-Mu''akhkhir','আল-মুয়াখখির','পশ্চাদবর্তীকারী',NULL);
INSERT INTO allah_names VALUES(73,'The First, The Beginning-less','The First','(57:3)','الأوَّلُ','Al-Awwal','আল-আউয়াল','অনাদি ও সর্বপ্রথম',NULL);
INSERT INTO allah_names VALUES(74,'The Last, The Endless','The Last','(57:3)','الآخِرُ','Al-Akhir','আল-আখির','অনন্ত ও সর্বশেষ',NULL);
INSERT INTO allah_names VALUES(75,'The Manifest, The Evident','The Manifest','(57:3)','الظَّاهِرُ','Az-Zahir','আয-যাহির','প্রকাশ্য',NULL);
INSERT INTO allah_names VALUES(76,'The Hidden, The Unmanifest','The Hidden','(57:3)','الْبَاطِنُ','Al-Batin','আল-বাতিন','অপ্রকাশ্য ও গুপ্ত',NULL);
INSERT INTO allah_names VALUES(77,'The Sole Governor, The Ruler','The Governor','(13:11)(22:7)','الْوَالِي','Al-Wali','আল-ওয়ালী','সর্বনিয়ন্তা ও শাসক',NULL);
INSERT INTO allah_names VALUES(78,'The Supremely Exalted','The Supreme One','(13:9)','الْمُتَعَالِي','Al-Muta''ali','আল-মুতাআলী','সর্বোচ্চ মর্যাদাবান',NULL);
INSERT INTO allah_names VALUES(79,'The Source of All Goodness','The Doer of Good','(52:28)','الْبَرُّ','Al-Barr','আল-বার্র','পরম কল্যাণকারী ও অনুগ্রহশীল',NULL);
INSERT INTO allah_names VALUES(80,'The Ever-Accepter of Repentance','The Guide to Repentence','(2:128)(4:64)(49:12)(110:3)','التَّوَابُ','At-Tawwab','আত-তাওয়াব','তওবা কবুলকারী',NULL);
INSERT INTO allah_names VALUES(81,'The Avenger, The Retributor','The Avenger','(32:22)(43:41)(44:16)','الْمُنْتَقِمُ','Al-Muntaqim','আল-মুনতাক্বিম','অপরাধীর শাস্তিদাতা',NULL);
INSERT INTO allah_names VALUES(82,'The Pardoner, The Effacer of Sins','The Forgiver','(4:99)(4:149)(22:60)','العَفُوُّ','Al-''Afuww','আল-আফুউ','মহাক্ষমাশীল ও মার্জনাকারী',NULL);
INSERT INTO allah_names VALUES(83,'The Compassionate, The All-Pitying','The Most Kind','(3:30)(9:117)(57:9)(59:10)','الرَّؤُوفُ','Ar-Ra''oof','আর-রাউফ','পরম কোমল হৃদয় ও দয়ালু',NULL);
INSERT INTO allah_names VALUES(84,'The Owner of Dominion and Sovereignty','The Sovereign of All','(3:26)','مَالِكُ الْمُلْكِ','Malik-ul-Mulk','মালিকুল মুলক','সমগ্র বিশ্বজগতের মালিক',NULL);
INSERT INTO allah_names VALUES(85,'The Lord of Majesty and Generosity','Possessor of Majesty and Bounty','(55:27)(55:78)','ذُوالْجَلاَلِ وَالإكْرَامِ','Dhul-Jalali wal-Ikram','যুল-জালালি ওয়াল-ইকরাম','মহিমাময় ও মহানুভব',NULL);
INSERT INTO allah_names VALUES(86,'The Equitable, The Requiter','The Equitable One','(7:29)(3:18)','الْمُقْسِطُ','Al-Muqsit','আল-মুকসিত','ন্যায়বিচারক',NULL);
INSERT INTO allah_names VALUES(87,'The Gatherer, The Unifier','The Gatherer','(3:9)','الْجَامِعُ','Al-Jami''','আল-জামি','একত্রকারী',NULL);
INSERT INTO allah_names VALUES(88,'The Self-Sufficient, The Wealthy','The Rich One','(3:97)(39:7)(47:38)(57:24)','الْغَنِيُّ','Al-Ghaniyy','আল-গানী','চির ধনী ও অভাবমুক্ত',NULL);
INSERT INTO allah_names VALUES(89,'The Enricher, The Emancipator','The Enricher','(9:28)','الْمُغْنِي','Al-Mughni','আল-মুগনী','অভাবমোচনকারী',NULL);
INSERT INTO allah_names VALUES(90,'The Preventer, The Defender','The Preventer of Harm','(67:21)','اَلْمَانِعُ','Al-Mani''','আল-মানি','প্রতিরোধকারী',NULL);
INSERT INTO allah_names VALUES(91,'The Creator of Harm (by His Will)','The Creator of Harm','(6:17)','الضَّارَّ','Ad-Darr','আদ-দার্র','অনিষ্টকারী (আল্লাহর হুকুমে)',NULL);
INSERT INTO allah_names VALUES(92,'The Creator of Good, The Propitious','The Bestower of Benefits','(30:37)','النَّافِعُ','An-Nafi''','আন-নাফি','কল্যাণকারী',NULL);
INSERT INTO allah_names VALUES(93,'The Light, The Illuminator','The Light','(24:35)','النُّورُ','An-Noor','আন-নূর','পরম জ্যোতি',NULL);
INSERT INTO allah_names VALUES(94,'The Guide, The Waymaker','The Guider','(25:31)','الْهَادِي','Al-Hadi','আল-হাদী','পথপ্রদর্শক',NULL);
INSERT INTO allah_names VALUES(95,'The Incomparable Originator','The Incomparable Originator','(2:117)(6:101)','الْبَدِيعُ','Al-Badi''','আল-বাদী','অপূর্ব সৃষ্টিজগতের উদ্ভাবক',NULL);
INSERT INTO allah_names VALUES(96,'The Everlasting, The Infinite','The Everlasting One','(55:27)','اَلْبَاقِي','Al-Baqi','আল-বাক্বী','চিরস্থায়ী ও অবিনশ্বর',NULL);
INSERT INTO allah_names VALUES(97,'The Supreme Inheritor of All','The Inheritor','(15:23)','الْوَارِثُ','Al-Warith','আল-ওয়ারিস','সকল কিছুর চূড়ান্ত উত্তরাধিকারী',NULL);
INSERT INTO allah_names VALUES(98,'The Guide to the Right Path','The Most Righteous Guide','(2:256)','الرَّشِيدُ','Ar-Rasheed','আর-রাশীদ','সঠিক পথের নির্দেশক',NULL);
INSERT INTO allah_names VALUES(99,'The Timeless, The Most Patient','The Patient One','(2:153)(3:200)(103:3)','الصَّبُورُ','As-Saboor','আস-সবূর','মহা ধৈর্যশীল',NULL);
COMMIT;
